/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx,css}',
  ],
  safelist: [
    'bg-dark-base',
    'bg-dark-secondary',
    'bg-dark-tertiary',
    'bg-neon-green',
    'bg-cyber-blue',
    'bg-neon-purple',
    'bg-neon-red',
    'bg-neon-orange',
    'bg-neon-yellow',
    'bg-neon-pink',
    'bg-cyber-gray',
    'bg-cyber-black',
    'bg-black',
    'bg-gray-900',
    'bg-gray-800',
    'text-neon-green',
    'text-cyber-blue',
    'text-neon-purple',
    'text-neon-red',
    'text-neon-orange',
    'text-neon-yellow',
    'text-cyber-gray',
    'text-white',
    'border-neon-green',
    'border-cyber-blue',
    'border-neon-purple',
    'border-neon-red',
    'hover:bg-neon-green/10',
    'hover:border-neon-green',
    'hover:text-neon-green',
    'hover:shadow-glow-green',
    'shadow-glow-green',
    'shadow-glow-blue',
    'shadow-glow-purple',
    'animate-matrix-rain',
    'animate-glow-pulse',
    'animate-glitch',
    'animate-scan-line',
    'animate-terminal-cursor',
    'animate-float',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-12',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-6',
    'col-span-8',
    'col-span-12',
    'cyber-interactive',
    'cyber-glow-green',
    'cyber-glow-blue',
    'cyber-glow-purple',
    'cyber-card',
    'cyber-button',
    'cyber-terminal',
    'cyber-section',
    'font-cyber',
    'font-terminal',
  ],
  theme: {
    extend: {
      colors: {
        'dark-base': '#1a1b26',
        'dark-secondary': '#282a36',
        'dark-tertiary': '#44475a',
        'neon-green': '#50fa7b',
        'cyber-blue': '#8be9fd',
        'neon-purple': '#bd93f9',
        'neon-pink': '#FF00FF',
        'neon-yellow': '#f1fa8c',
        'neon-orange': '#ffb86c',
        'neon-red': '#ff5555',
        'terminal-green': '#0F0',
        'matrix-green': '#00FF41',
        'cyber-black': '#0D0D0D',
        'cyber-white': '#F0F0F0',
        'cyber-gray': '#6272a4',
        'error-red': '#ff5555',
      },
      fontFamily: {
        'mono': ['JetBrains Mono', 'monospace'],
        'cyber': ['Share Tech Mono', 'monospace'],
        'terminal': ['Fira Code', 'monospace'],
      },
      animation: {
        'matrix-rain': 'matrix-rain 20s linear infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'glitch': 'glitch 1s linear infinite',
        'scan-line': 'scan-line 2s linear infinite',
        'terminal-cursor': 'terminal-cursor 1s step-end infinite',
        'float': 'float 3s ease-in-out infinite',
        'security-scan': 'security-scan 4s linear infinite',
        'node-pulse': 'node-pulse 2s infinite',
        'holographic': 'holographic-shift 6s linear infinite',
        'neon-border': 'neon-border 2s infinite alternate',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-fast': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'matrix': 'matrix 20s linear infinite',
        'typing': 'typing 3.5s steps(40, end), blink .75s step-end infinite',
        'scan': 'scan 4s linear infinite',
        'glitch': 'glitch 3s infinite',
        'rotate-slow': 'rotate 10s linear infinite',
        'pulse-lite': 'pulse-lite 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow-lite': 'glow-lite 3s ease-in-out infinite alternate',
        'matrix-lite': 'matrix-lite 30s linear infinite',
        'glitch-lite': 'glitch-lite 5s infinite',
      },
      keyframes: {
        'matrix-rain': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: 0.8, boxShadow: '0 0 5px rgba(80, 250, 123, 0.5)' },
          '50%': { opacity: 1, boxShadow: '0 0 15px rgba(80, 250, 123, 0.8)' },
        },
        'glitch': {
          '0%, 100%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 2px)' },
          '40%': { transform: 'translate(-2px, -2px)' },
          '60%': { transform: 'translate(2px, 2px)' },
          '80%': { transform: 'translate(2px, -2px)' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'terminal-cursor': {
          '0%, 100%': { opacity: 0 },
          '50%': { opacity: 1 },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'security-scan': {
          '0%': { transform: 'translateY(0) scale(1)', opacity: 0 },
          '10%': { opacity: 0.8 },
          '90%': { opacity: 0.8 },
          '100%': { transform: 'translateY(100%) scale(0.8)', opacity: 0 },
        },
        'node-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: 1 },
          '50%': { transform: 'scale(1.05)', opacity: 0.8 },
        },
        'holographic-shift': {
          '0%': { filter: 'hue-rotate(0deg) brightness(1)' },
          '25%': { filter: 'hue-rotate(45deg) brightness(1.1)' },
          '50%': { filter: 'hue-rotate(90deg) brightness(1)' },
          '75%': { filter: 'hue-rotate(135deg) brightness(1.1)' },
          '100%': { filter: 'hue-rotate(180deg) brightness(1)' },
        },
        'neon-border': {
          '0%': { boxShadow: '0 0 5px #50fa7b, 0 0 10px #50fa7b, 0 0 15px #50fa7b, 0 0 20px #50fa7b' },
          '100%': { boxShadow: '0 0 10px #8be9fd, 0 0 20px #8be9fd, 0 0 30px #8be9fd, 0 0 40px #8be9fd' },
        },
        glow: {
          '0%': { textShadow: '0 0 10px #50fa7b, 0 0 20px #50fa7b' },
          '100%': { textShadow: '0 0 5px #50fa7b, 0 0 10px #50fa7b, 0 0 15px #50fa7b' },
        },
        matrix: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        typing: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        blink: {
          '0%, 100%': { borderColor: 'transparent' },
          '50%': { borderColor: '#50fa7b' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        glitch: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-5px)' },
          '40%': { transform: 'translateX(5px)' },
          '60%': { transform: 'translateX(-5px)' },
          '80%': { transform: 'translateX(5px)' },
        },
        'pulse-lite': {
          '0%, 100%': { opacity: '0.7' },
          '50%': { opacity: '0.4' },
        },
        'glow-lite': {
          '0%': { textShadow: '0 0 5px #50fa7b' },
          '100%': { textShadow: '0 0 8px #50fa7b' },
        },
        'matrix-lite': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'glitch-lite': {
          '0%, 100%': { transform: 'translateX(0)' },
          '33%': { transform: 'translateX(-3px)' },
          '66%': { transform: 'translateX(3px)' },
        },
      },
      boxShadow: {
        'glow-green': '0 0 5px rgba(80, 250, 123, 0.7), 0 0 10px rgba(80, 250, 123, 0.4)',
        'glow-blue': '0 0 5px rgba(139, 233, 253, 0.7), 0 0 10px rgba(139, 233, 253, 0.4)',
        'glow-purple': '0 0 5px rgba(189, 147, 249, 0.7), 0 0 10px rgba(189, 147, 249, 0.4)',
        'glow-red': '0 0 5px rgba(255, 85, 85, 0.7), 0 0 10px rgba(255, 85, 85, 0.4)',
        'cyber-card': '0 4px 6px rgba(0, 0, 0, 0.1), 0 0 0 1px rgba(80, 250, 123, 0.1)',
        'cyber-terminal': '0 0 0 1px rgba(139, 233, 253, 0.2), inset 0 0 10px rgba(139, 233, 253, 0.1)',
        'neon-green': '0 0 5px #50fa7b, 0 0 10px #50fa7b',
        'neon-blue': '0 0 5px #8be9fd, 0 0 10px #8be9fd',
        'neon-purple': '0 0 5px #bd93f9, 0 0 10px #bd93f9',
      },
      textShadow: {
        'neon-green': '0 0 5px #50fa7b, 0 0 10px #50fa7b',
        'neon-blue': '0 0 5px #8be9fd, 0 0 10px #8be9fd',
        'neon-purple': '0 0 5px #bd93f9, 0 0 10px #bd93f9',
        'neon-green-lite': '0 0 5px #50fa7b',
        'neon-blue-lite': '0 0 5px #8be9fd',
        'neon-purple-lite': '0 0 5px #bd93f9',
      },
      backgroundImage: {
        'cyber-grid': "url('/images/cyber-grid.svg')",
        'matrix-rain': "url('/images/matrix-rain.png')",
        'cyber-pattern': "linear-gradient(to right, rgba(40, 42, 54, 0.8), rgba(40, 42, 54, 0.8)), url('/images/cyber-pattern.svg')",
        'gradient-neon': 'linear-gradient(45deg, #50fa7b, #8be9fd)',
        'cyber-grid': 'linear-gradient(rgba(80, 250, 123, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(80, 250, 123, 0.1) 1px, transparent 1px)',
        'radial-glow': 'radial-gradient(circle at center, rgba(80, 250, 123, 0.2) 0%, rgba(0, 0, 0, 0) 70%)',
      },
      backgroundSize: {
        'cyber-grid-sm': '20px 20px',
        'cyber-grid-md': '40px 40px',
        'cyber-grid-lg': '60px 60px',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        '.text-shadow-neon-green': {
          textShadow: '0 0 5px #50fa7b, 0 0 10px #50fa7b',
        },
        '.text-shadow-neon-blue': {
          textShadow: '0 0 5px #8be9fd, 0 0 10px #8be9fd',
        },
        '.text-shadow-neon-purple': {
          textShadow: '0 0 5px #bd93f9, 0 0 10px #bd93f9',
        },
        '.text-shadow-neon-green-lite': {
          textShadow: '0 0 5px #50fa7b',
        },
        '.text-shadow-neon-blue-lite': {
          textShadow: '0 0 5px #8be9fd',
        },
        '.text-shadow-neon-purple-lite': {
          textShadow: '0 0 5px #bd93f9',
        },
        '.text-gradient-neon': {
          background: 'linear-gradient(45deg, #50fa7b, #8be9fd)',
          '-webkit-background-clip': 'text',
          '-webkit-text-fill-color': 'transparent',
        },
        '.cyber-grid-bg': {
          backgroundImage: 'linear-gradient(to right, #282a36 1px, transparent 1px), linear-gradient(to bottom, #282a36 1px, transparent 1px)',
          backgroundSize: '20px 20px',
          backgroundPosition: 'center center',
        },
        '.gpu-accelerated': {
          'will-change': 'transform',
          'transform': 'translateZ(0)',
          'backface-visibility': 'hidden',
        },
        '.content-optimized': {
          'content-visibility': 'auto',
          'contain': 'content',
        },
      };
      
      addUtilities(newUtilities, ['responsive', 'hover']);
    },
  ],
}